# Generated by Django 6.0.3 on 2026-04-15 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='productos/')),
                ('numero_producto', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='El precio debe ser mayor a 0.')])),
                ('stock', models.PositiveIntegerField()),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
