# Generated by Django 6.0.3 on 2026-04-13 23:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_productos_imagen_alter_productos_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='marca',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
