# Generated by Django 6.0.3 on 2026-03-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
