# Generated by Django 6.0.3 on 2026-03-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_clientes_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='numero_telefonico',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
