# Generated by Django 6.0.3 on 2026-03-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='numero_telefonico',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
